<?php

use Illuminate\Database\Seeder;
use App\Ward;
class WardsTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        //
         $wards = [

        ['county_id' => 1,'name' =>"Changamwe"],
        ['county_id' => 1, 'name' =>"JOMVU"],
        ['county_id' => 1, 'name' =>"KISAUNI"],
        ['county_id' => 1, 'name' =>"NYALI"],
        ['county_id' => 1, 'name' =>"LIKONI"],
        ['county_id' => 1, 'name' =>"MVITA"],
        ['county_id' => 2, 'name' =>'MSAMBWENI'],
        ['county_id' => 2, 'name' =>'LUNGALUNGA'],
        ['county_id' => 2, 'name' =>'MATUGA'],
        ['county_id' => 2, 'name' =>'KINANGO'],
        ['county_id' => 3, 'name' =>'KILIFI NORTH'],
        ['county_id' => 3, 'name' =>'KILIFI SOUTH'],
        ['county_id' => 3, 'name' =>'KALOLENI'],
        ['county_id' => 3, 'name' =>'RABAI'],
        ['county_id' => 3, 'name' =>'GANZE'],
        ['county_id' => 3, 'name' =>'MALINDI'],
        ['county_id' => 3, 'name' =>'MAGARINI'],
        ['county_id' => 4, 'name' =>"GARSEN"],
        ['county_id' => 4, 'name' =>"GALOLE"],
        ['county_id' => 4, 'name' =>"BURA"],
        ['county_id' => 5, 'name' =>"LAMU EAST"],
        ['county_id' => 5, 'name' =>"LAMU WEST"],
        ['county_id' => 6, 'name' =>"TAVETA"],
        ['county_id' => 6, 'name' =>"WUNDANYI"],
        ['county_id' => 6, 'name' =>"MWATATE"],
        ['county_id' => 6, 'name' =>"VOI"],
        ['county_id' => 7, 'name' =>"WAJIR NORTH"],
        ['county_id' => 7, 'name' =>"WAJIR EAST"],
        ['county_id' => 7, 'name' =>"TARBAJ"],
        ['county_id' => 7, 'name' =>"WAJIR WEST"],
        ['county_id' => 7, 'name' =>"ELDAS"],
        ['county_id' => 7, 'name' =>"WAJIR SOUTH"],
        ['county_id' => 8, 'name' =>"WAJIR NORTH"],
        ['county_id' => 8, 'name' =>"WAJIR EAST"],
        ['county_id' => 8, 'name' =>"TARBAJ"],
        ['county_id' => 8, 'name' =>"WAJIR WEST"],
        ['county_id' => 8, 'name' =>"ELDAS"],
        ['county_id' => 8, 'name' =>"WAJIR SOUTH"],
        ['county_id' => 9, 'name' =>"MANDERA WEST"],
        ['county_id' => 9, 'name' =>"BANISSA"],
        ['county_id' => 9, 'name' =>"MANDERA NORTH"],
        ['county_id' => 9, 'name' =>"MANDERA SOUTH"],
        ['county_id' => 9, 'name' =>"MANDERA EAST"],
        ['county_id' => 9, 'name' =>"LAFEY"],
        ['county_id' => 10, 'name' =>"MOYALE"],
        ['county_id' => 10, 'name' =>"NORTH HORR"],
        ['county_id' => 10, 'name' =>"SAKU"],
        ['county_id' => 10, 'name' =>"LAISAMIS"],
        ['county_id' => 11, 'name' =>"ISIOLO NORTH"],
        ['county_id' => 11, 'name' =>"ISIOLO SOUTH"],
        ['county_id' => 12, 'name' =>"IGEMBE SOUTH"],
        ['county_id' => 12, 'name' =>"IGEMBE CENTRAL"],
        ['county_id' => 12, 'name' =>"IGEMBE NORTH"],
        ['county_id' => 12, 'name' =>"TIGANIA WEST"],
        ['county_id' => 12, 'name' =>"TIGANIA EAST"],
        ['county_id' => 12, 'name' =>"NORTH IMENTI"],
        ['county_id' => 12, 'name' =>"BUURI"],
        ['county_id' => 12, 'name' =>"CENTRAL IMENTI"],
        ['county_id' => 12, 'name' =>"SOUTH IMENTI"],
        ['county_id' => 13, 'name' =>"MAARA"],
        ['county_id' => 13, 'name' =>"CHUKA/IGAMBANG'OMBE"],
        ['county_id' => 13, 'name' =>"THARAKA"],
        ['county_id' => 14, 'name' => "MANYATTA"],
        ['county_id' => 14, 'name' => "RUNYENJES"],
        ['county_id' => 14, 'name' => "MBEERE SOUTH"],
        ['county_id' => 14, 'name' => "MBEERE NORTH"],
        ['county_id' => 15, 'name' => "MWINGI NORTH"],
        ['county_id' => 15, 'name' => "MWINGI WEST"],
        ['county_id' => 15, 'name' => "MWINGI CENTRAL"],
        ['county_id' => 15, 'name' => "KITUI WEST"],
        ['county_id' => 15, 'name' => "KITUI RURAL"],
        ['county_id' => 15, 'name' => "KITUI CENTRAL"],
        ['county_id' => 15, 'name' => "KITUI EAST"],
        ['county_id' => 15, 'name' => "KITUI SOUTH"],
        ['county_id' => 16, 'name' => "MASINGA"],
        ['county_id' => 16, 'name' => "YATTA"],
        ['county_id' => 16, 'name' => "KANGUNDO"],
        ['county_id' => 16, 'name' => "MATUNGULU"],
        ['county_id' => 16, 'name' => "KATHIANI"],
        ['county_id' => 16, 'name' => "MACHAKOS TOWN"],
        ['county_id' => 16, 'name' => "MAVOKO"],
        ['county_id' => 16, 'name' => "MWALA"],
        ['county_id' => 17, 'name' => "MBOONI"],
        ['county_id' => 17, 'name' => "KILOME"],
        ['county_id' => 17, 'name' => "KAITI"],
        ['county_id' => 17, 'name' => "MAKUENI"],
        ['county_id' => 17, 'name' => "KIBWEZI WEST"],
        ['county_id' => 17, 'name' => "KIBWEZI EAST"],
        ['county_id' => 18, 'name' => "KINANGOP"],
        ['county_id' => 18, 'name' => "KIPIPIRI"],
        ['county_id' => 18, 'name' => "OL KALOU"],
        ['county_id' => 18, 'name' => "OL JOROK"],
        ['county_id' => 18, 'name' => "NDARAGWA"],
        ['county_id' => 19, 'name' => "TETU"],
        ['county_id' => 19, 'name' => "KIENI"],
        ['county_id' => 19, 'name' => "MATHIRA"],
        ['county_id' => 19, 'name' => "OTHAYA"],
        ['county_id' => 19, 'name' => "MUKURWEINI"],
        ['county_id' => 19, 'name' => "NYERI TOWN"],
        ['county_id' => 20, 'name' => "MWEA"],
        ['county_id' => 20, 'name' => "GICHUGU"],
        ['county_id' => 20, 'name' => "NDIA"],
        ['county_id' => 20, 'name' => "KIRINYAGA CENTRAL"],
        ['county_id' => 21, 'name' => "KANGEMA"],
        ['county_id' => 21, 'name' => "MATHIOYA"],
        ['county_id' => 21, 'name' => "KIHARU"],
        ['county_id' => 21, 'name' => "KIGUMO"],
        ['county_id' => 21, 'name' => "MARAGWA"],
        ['county_id' => 21, 'name' => "KANDARA"],
        ['county_id' => 21, 'name' => "GATANGA"],
        ['county_id' => 22, 'name' => "GATUNDU SOUTH"],
        ['county_id' => 22, 'name' => "GATUNDU NORTH"],
        ['county_id' => 22, 'name' => "JUJA"],
        ['county_id' => 22, 'name' => "THIKA TOWN"],
        ['county_id' => 22, 'name' => "RUIRU"],
        ['county_id' => 22, 'name' => "GITHUNGURI"],
        ['county_id' => 22, 'name' => "KIAMBU"],
        ['county_id' => 22, 'name' => "KIAMBAA"],
        ['county_id' => 22, 'name' => "KABETE"],
        ['county_id' => 22, 'name' => "KIKUYU"],
        ['county_id' => 22, 'name' => "LIMURU"],
        ['county_id' => 22, 'name' => "LARI"],
        ['county_id' => 23, 'name' => "TURKANA NORTH"],
        ['county_id' => 23, 'name' => "TURKANA WEST"],
        ['county_id' => 23, 'name' => "TURKANA CENTRAL"],
        ['county_id' => 23, 'name' => "LOIMA"],
        ['county_id' => 23, 'name' => "TURKANA SOUTH"],
        ['county_id' => 23, 'name' => "TURKANA EAST"],
        ['county_id' => 24, 'name' => "KAPENGURIA"],
        ['county_id' => 24, 'name' => "SIGOR"],
        ['county_id' => 24, 'name' => "KACHELIBA"],
        ['county_id' => 24, 'name' => "POKOT SOUTH"],
        ['county_id' => 25, 'name' => "SAMBURU WEST"],
        ['county_id' => 25, 'name' => "SAMBURU NORTH"],
        ['county_id' => 25, 'name' => "SAMBURU EAST"],
        ['county_id' => 26, 'name' => "KWANZA"],
        ['county_id' => 26, 'name' => "ENDEBESS"],
        ['county_id' => 26, 'name' => "SABOTI"],
        ['county_id' => 26, 'name' => "KIMININI"],
        ['county_id' => 26, 'name' => "CHERANGANY"],
        ['county_id' => 27, 'name' => "SOY"],
        ['county_id' => 27, 'name' => "TURBO"],
        ['county_id' => 27, 'name' => "MOIBEN"],
        ['county_id' => 27, 'name' => "AINABKOI"],
        ['county_id' => 27, 'name' => "KAPSERET"],
        ['county_id' => 27, 'name' => "KESSES"],
        ['county_id' => 28, 'name' => "MARAKWET EAST"],
        ['county_id' => 28, 'name' => "MARAKWET WEST"],
        ['county_id' => 28, 'name' => "KEIYO NORTH"],
        ['county_id' => 28, 'name' => "KEIYO SOUTH"],
        ['county_id' => 29, 'name' => "TINDERET"],
        ['county_id' => 29, 'name' => "ALDAI"],
        ['county_id' => 29, 'name' => "NANDI HILLS"],
        ['county_id' => 29, 'name' => "CHESUMEI"],
        ['county_id' => 29, 'name' => "EMGWEN"],
        ['county_id' => 29, 'name' => "MOSOP"],
        ['county_id' => 30, 'name' => "BARINGO SOUTH"],
        ['county_id' => 30, 'name' => "MOGOTIO"],
        ['county_id' => 30, 'name' => "ELDAMA RAVINE"],
        ['county_id' => 30, 'name' => "TIATY"],
        ['county_id' => 30, 'name' => "BARINGO NORTH"],
        ['county_id' => 30, 'name' => "BARINGO CENTRAL"],
        ['county_id' => 31, 'name' => "LAIKIPIA WEST"],
        ['county_id' => 31, 'name' => "LAIKIPIA EAST"],
        ['county_id' => 31, 'name' => "LAIKIPIA NORTH"],
        ['county_id' => 32, 'name' => "MOLO"],
        ['county_id' => 32, 'name' => "NJORO"],
        ['county_id' => 32, 'name' => "NAIVASHA"],
        ['county_id' => 32, 'name' => "GILGIL"],
        ['county_id' => 32, 'name' => "KURESOI SOUTH"],
        ['county_id' => 32, 'name' => "KURESOI NORTH"],
        ['county_id' => 32, 'name' => "SUBUKIA"],
        ['county_id' => 32, 'name' => "RONGAI"],
        ['county_id' => 32, 'name' => "BAHATI"],
        ['county_id' => 32, 'name' => "NAKURU TOWN WEST"],
        ['county_id' => 32, 'name' => "NAKURU TOWN EAST"],
        ['county_id' => 33, 'name' => "KILGORIS"],
        ['county_id' => 33, 'name' => "EMURUA DIKIRR"],
        ['county_id' => 33, 'name' => "NAROK NORTH"],
        ['county_id' => 33, 'name' => "NAROK EAST"],
        ['county_id' => 33, 'name' => "NAROK SOUTH"],
        ['county_id' => 33, 'name' => "NAROK WEST"],
        ['county_id' => 34, 'name' => "KAJIADO NORTH"],
        ['county_id' => 34, 'name' => "KAJIADO CENTRAL"],
        ['county_id' => 34, 'name' => "KAJIADO EAST"],
        ['county_id' => 34, 'name' => "KAJIADO WEST"],
        ['county_id' => 34, 'name' => "KAJIADO SOUTH"],
        ['county_id' => 35, 'name' => "KIPKELION EAST"],
        ['county_id' => 35, 'name' => "KIPKELION WEST"],
        ['county_id' => 35, 'name' => "AINAMOI"],
        ['county_id' => 35, 'name' => "BURETI"],
        ['county_id' => 35, 'name' => "BELGUT"],
        ['county_id' => 35, 'name' => "SIGOWET/SOIN"],
        ['county_id' => 36, 'name' => "SOTIK"],
        ['county_id' => 36, 'name' => "CHEPALUNGU"],
        ['county_id' => 36, 'name' => "BOMET EAST"],
        ['county_id' => 36, 'name' => "BOMET CENTRAL"],
        ['county_id' => 36, 'name' => "KONOIN"],
        ['county_id' => 37, 'name' => "LUGARI"],
        ['county_id' => 37, 'name' => "LIKUYANI"],
        ['county_id' => 37, 'name' => "MALAVA"],
        ['county_id' => 37, 'name' => "LURAMBI"],
        ['county_id' => 37, 'name' => "NAVAKHOLO"],
        ['county_id' => 37, 'name' => "MUMIAS WEST"],
        ['county_id' => 37, 'name' => "MUMIAS EAST"],
        ['county_id' => 37, 'name' => "MATUNGU"],
        ['county_id' => 37, 'name' => "BUTERE"],
        ['county_id' => 37, 'name' => "KHWISERO"],
        ['county_id' => 37, 'name' => "SHINYALU"],
        ['county_id' => 37, 'name' => "IKOLOMANI"],
        ['county_id' => 38, 'name' => "vihiga"],
        ['county_id' => 38, 'name' => "sabatia"],
        ['county_id' => 38, 'name' => "Hamisi"],
        ['county_id' => 38, 'name' => "Luanda"],
        ['county_id' => 38, 'name' => "Emuhaya"],
        ['county_id' => 39,  'name'=>'MT. ELGON'],
        ['county_id' => 39, 'name'=>'SIRISIA'],
        ['county_id' => 39, 'name'=>'KABUCHAI'],
        ['county_id' => 39,'name'=>'BUMULA'],
        ['county_id' => 39,'name'=>'KANDUYI'],
        ['county_id' => 39,'name'=>'WEBUYE EAST'],
        ['county_id' => 39, 'name'=>'WEBUYE WEST'],
        ['county_id' => 39, 'name'=>'KIMILILI'],
        ['county_id' => 39, 'name'=>'TONGAREN'],
        ['county_id' => 40, 'name' => "Teso North"],
        ['county_id' => 40, 'name' => "TESO NORTH"],
        ['county_id' => 40, 'name' => "MATAYOS"],
        ['county_id' => 40, 'name' => "BUTULA"],
        ['county_id' => 40, 'name' => "FUNYULA"],
        ['county_id' => 41, 'name' => "UGUNJA"],
        ['county_id' => 41, 'name' => "GEM"],
        ['county_id' => 41, 'name' => "BONDO"],
        ['county_id' => 41, 'name' => "RARIEDA"],
        ['county_id' => 42, 'name' => "KISUMU EAST"],
        ['county_id' => 42, 'name' => "KISUMU WEST"],
        ['county_id' => 42, 'name' => "KISUMU CENTRAL"],
        ['county_id' => 42, 'name' => "SEME"],
        ['county_id' => 42, 'name' => "NYANDO"],
        ['county_id' => 42, 'name' => "MUHORONI"],
        ['county_id' => 42, 'name' => "NYAKACH"],
        ['county_id' => 44, 'name' => "AWENDO"],
        ['county_id' => 44, 'name' => "SUNA EAST"],
        ['county_id' => 44, 'name' => "SUNA WEST"],
        ['county_id' => 44, 'name' => "URIRI"],
        ['county_id' => 44, 'name' => "NYATIKE"],
        ['county_id' => 44, 'name' => "KURIA WEST"],
        ['county_id' => 44, 'name' => "KURIA EAST"],
        ['county_id' => 45, 'name' => "BONCHARI"],
        ['county_id' => 45, 'name' => "SOUTH MUGIRANGO"],
        ['county_id' => 45, 'name' => "BOMACHOGE BORABU"],
        ['county_id' => 45, 'name' => "BOBASI"],
        ['county_id' => 45, 'name' => "BOMACHOGE CHACHE"],
        ['county_id' => 45, 'name' => "NYARIBARI MASABA"],
        ['county_id' => 45, 'name' => "NYARIBARI CHACHE"],
        ['county_id' => 45, 'name' => "KITUTU CHACHE NORTH"],
        ['county_id' => 45, 'name' => "KITUTU CHACHE SOUTH"],
        ['county_id' => 46, 'name' => "KITUTU MASABA"],
        ['county_id' => 46, 'name' => "WEST MUGIRANGO"],
        ['county_id' => 46, 'name' => "NORTH MUGIRANGO"],
        ['county_id' => 46, 'name' => "BORABU"],
        ['county_id' => 47, 'name' => "WESTLANDS"],
        ['county_id' => 47, 'name' => "DAGORETTI NORTH"],
        ['county_id' => 47, 'name' => "DAGORETTI SOUTH"],
        ['county_id' => 47, 'name' => "LANGATA"],
        ['county_id' => 47, 'name' => "KIBRA"],
        ['county_id' => 47, 'name' => "ROYSAMBU"],
        ['county_id' => 47, 'name' => "KASARANI"],
        ['county_id' => 47, 'name' => "RUARAKA"],
        ['county_id' => 47, 'name' => "EMBAKASI SOUTH"],
        ['county_id' => 47, 'name' => "EMBAKASI NORTH"],
        ['county_id' => 47, 'name' => "EMBAKASI CENTRAL"],
        ['county_id' => 47, 'name' => "EMBAKASI EAST"],
        ['county_id' => 47, 'name' => "EMBAKASI WEST"],
        ['county_id' => 47, 'name' => "MAKADARA"],
        ['county_id' => 47, 'name' => "STAREHE"],
        ['county_id' => 47, 'name' => "MATHARE"],

         ];

        foreach ($wards as $ward) {

            Ward::create($ward);
        }


    }
}
