<?php

use Illuminate\Database\Seeder;
use App\Ward;
class WardsTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        //
         $wards = [
                'county_id' => 1, 'name' => "Mikindani",
                'county_id' => 1, 'name' => "Miritini",
                'county_id' => 1, 'name' => "Port Reitz",
                'county_id' => 1, 'name' => "Tudor Estate",
                'county_id' => 1, 'name' => "Jomvu Kuu",
                'county_id' => 1, 'name' => "Changamwe",
                'county_id' => 1, 'name' => "Tudor Four",
                'county_id' => 1, 'name' => "Bamburi",
                'county_id' => 1, 'name' => "Frere Town",
                'county_id' => 1, 'name' => "Kizingo",
                'county_id' => 1, 'name' => "Kongowea",
                'county_id' => 1, 'name' => "Maweni",
                'county_id' => 1, 'name' => "Mjambere",
                'county_id' => 1, 'name' => "Makadara",
                'county_id' => 1, 'name' => "Mwakirunge",
                'county_id' => 1, 'name' => "Bofu",
                'county_id' => 1, 'name' => "Ganjoni",
                'county_id' => 1, 'name' => "Mtongwe",
                'county_id' => 1, 'name' => "Shika Adabu",
                'county_id' => 1, 'name' => "Bondeni",
                'county_id' => 1, 'name' => "King'orani",
                'county_id' => 1, 'name' => "Majengo",
                'county_id' => 1, 'name' => "Shimanzi",
                'county_id' => 1, 'name' => "Tononoka",
                'county_id' => 2, 'name' =>"Dzombo",
                'county_id' => 2, 'name' =>"Kasemeni",
                'county_id' => 2, 'name' =>"Kikoneni",
                'county_id' => 2, 'name' =>"Kingwende",
                'county_id' => 2, 'name' =>"Kinondo",
                'county_id' => 2, 'name' =>"Msambweni",
                'county_id' => 2, 'name' =>"Mwereni",
                'county_id' => 2, 'name' =>"Pongwe",
                'county_id' => 2, 'name' =>"Vanga",
                'county_id' => 2, 'name' =>"Golini",
                'county_id' => 2, 'name' =>"Kubo South",
                'county_id' => 2, 'name' =>"Kwale",
                'county_id' => 2, 'name' =>"Mazumalume",
                'county_id' => 2, 'name' =>"Mbuguni",
                'county_id' => 2, 'name' =>"Mkongani",
                'county_id' => 2, 'name' =>"Mwaluphamba",
                'county_id' => 2, 'name' =>"Mwamgunga",
                'county_id' => 2, 'name' =>"Tiwi",
                'county_id' => 2, 'name' =>"Vuga",
                'county_id' => 2, 'name' =>"Waa",
                'county_id' => 2, 'name' =>"Ziwani",
                'county_id' => 2, 'name' =>"Chengoni",
                'county_id' => 2, 'name' =>"Kasemeni",
                'county_id' => 2, 'name' =>"Kinango",
                'county_id' => 2, 'name' =>"Taru",
                'county_id' => 2, 'name' =>"Gandini",
                'county_id' => 2, 'name' =>"Mwatate",
                'county_id' => 2, 'name' =>"Ndavaya",
                'county_id' => 2, 'name' =>"Makamini",
                'county_id' => 2, 'name' =>"Vigurungani",
                'county_id' => 3, 'name' =>"Mugumo-wa-patsa",
                'county_id' => 3, 'name' =>"Mwanamwinga",
                'county_id' => 3, 'name' =>"Rabai",
                'county_id' => 3, 'name' =>"Ribe",
                'county_id' => 3, 'name' =>"Ruruma",
                'county_id' => 3, 'name' =>"Tsangatsini",
                'county_id' => 3, 'name' =>"Bamba",
                'county_id' => 3, 'name' =>"Ganze",
                'county_id' => 3, 'name' =>"Jaribuni",
                'county_id' => 3, 'name' =>"Sokoke",
                'county_id' => 3, 'name' =>"Barani",
                'county_id' => 3, 'name' =>"Ganda",
                'county_id' => 3, 'name' =>"Gede",
                'county_id' => 3, 'name' =>"Kijiwetanga",
                'county_id' => 3, 'name' =>"Madunguni",
                'county_id' => 3, 'name' =>"Malimo",
                'county_id' => 3, 'name' =>"Malindi Central",
                'county_id' => 3, 'name' =>"Malindi North",
                'county_id' => 3, 'name' =>"Malindi South",
                'county_id' => 3, 'name' =>"Watamu",
                'county_id' => 3, 'name' =>"Chakama",
                'county_id' => 3, 'name' =>"Jilore",
                'county_id' => 3, 'name' =>"Lango Mbaya",
                'county_id' => 3, 'name' =>"Adu",
                'county_id' => 3, 'name' =>"Bungale",
                'county_id' => 3, 'name' =>"Dagamra",
                'county_id' => 3, 'name' =>"Fundi-issa",
                'county_id' => 3, 'name' =>"Garashi",
                'county_id' => 3, 'name' =>"Gongoni",
                'county_id' => 3, 'name' =>"Magarini",
                'county_id' => 4, 'name' =>"Marafa",
                'county_id' => 4, 'name' =>"Assa",
                'county_id' => 4, 'name' =>"Bilisa",
                'county_id' => 4, 'name' =>"Garsen Central",
                'county_id' => 4, 'name' =>"Garsen South",
                'county_id' => 4, 'name' =>"Kipini East",
                'county_id' => 4, 'name' =>"Kipini West",
                'county_id' => 4, 'name' =>"Ndera",
                'county_id' => 4, 'name' =>"Salama",
                'county_id' => 4, 'name' =>"Shirikisho",
                'county_id' => 4, 'name' =>"Chewani",
                'county_id' => 4, 'name' =>"Chifiri",
                'county_id' => 4, 'name' =>"Gwano",
                'county_id' => 4, 'name' =>"Kinakomba",
                'county_id' => 4, 'name' =>"Milalulu",
                'county_id' => 4, 'name' =>"Ndura",
                'county_id' => 4, 'name' =>"Wayu",
                'county_id' => 4, 'name' =>"Mikinduni",
                'county_id' => 4, 'name' =>"Bangale",
                'county_id' => 4, 'name' =>"Chewele",
                'county_id' => 4, 'name' =>"Hirimani",
                'county_id' => 4, 'name' =>"Kamaguru",
                'county_id' => 4, 'name' =>"Madogo South",
                'county_id' => 4, 'name' =>"Mbalambala",
                'county_id' => 4, 'name' =>"Nanighi",
                'county_id' => 4, 'name' =>"Saka",
                'county_id' => 4, 'name' =>"Sala",
                'county_id' => 5, 'name' =>"Basuba",
                'county_id' => 5, 'name' =>"Faza",
                'county_id' => 5, 'name' =>"Kiunga",
                'county_id' => 5, 'name' =>"Kizingitini West",
                'county_id' => 5, 'name' =>"Ndau",
                'county_id' => 5, 'name' =>"Siyu",
                'county_id' => 5, 'name' =>"Baharini",
                'county_id' => 5, 'name' =>"Dide Waride",
                'county_id' => 5, 'name' =>"Magogoni",
                'county_id' => 5, 'name' =>"Hongwe",
                'county_id' => 5, 'name' =>"Langoni",
                'county_id' => 5, 'name' =>"Mapenya",
                'county_id' => 5, 'name' =>"Mkomani",
                'county_id' => 5, 'name' =>"Mkunumbi",
                'county_id' => 5, 'name' =>"Mokowe",
                'county_id' => 5, 'name' =>"Mpeketoni",
                'county_id' => 5, 'name' =>"Witu",
                'county_id' => 6, 'name' => "Chala",
                'county_id' => 6, 'name' => "Kitobo",
                'county_id' => 6, 'name' => "Mahoo",
                'county_id' => 6, 'name' => "Mboghoni",
                'county_id' => 6, 'name' => "Taveta North",
                'county_id' => 6, 'name' => "Taveta South",
                'county_id' => 6, 'name' => "Mwanda",
                'county_id' => 6, 'name' => "Werugha",
                'county_id' => 6, 'name' => "Wumingu",
                'county_id' => 6, 'name' => "Wundanyi",
                'county_id' => 6, 'name' => "Kighononyi",
                'county_id' => 6, 'name' => "Bura",
                'county_id' => 6, 'name' => "Chawia",
                'county_id' => 6, 'name' => "Mwachabo",
                'county_id' => 6, 'name' => "Mwakitau",
                'county_id' => 6, 'name' => "Mwatate",
                'county_id' => 6, 'name' => "Rong'e",
                'county_id' => 6, 'name' => "Rong'e Juu",
                'county_id' => 7, 'name' =>"Waberi",
                'county_id' => 7, 'name' =>"Galbet",
                'county_id' => 7, 'name' =>"Township",
                'county_id' => 7, 'name' =>"Iftin",
                'county_id' => 7, 'name' =>"Abakaile",
                'county_id' => 7, 'name' =>"Alango-Arba",
                'county_id' => 7, 'name' =>"Benane",
                'county_id' => 7, 'name' =>"Dadaab",
                'county_id' => 7, 'name' =>"Dagahaley",
                'county_id' => 7, 'name' =>"Damajale",
                'county_id' => 7, 'name' =>"Garufa",
                'county_id' => 7, 'name' =>"Goreale",
                'county_id' => 7, 'name' =>"Liboi",
                'county_id' => 7, 'name' =>"Modogashe",
                'county_id' => 7, 'name' =>"Bura",
                'county_id' => 7, 'name' =>"Fafi",
                'county_id' => 7, 'name' =>"Jara Jila",
                'county_id' => 7, 'name' =>"Masabubu",
                'county_id' => 7, 'name' =>"Nanighi",
                'county_id' => 7, 'name' =>"Welmerer",
                'county_id' => 7, 'name' =>"Ijara",
                'county_id' => 7, 'name' =>"Korisa",
                'county_id' => 7, 'name' =>"Kotile",
                'county_id' => 7, 'name' =>"Masalani",
                'county_id' => 7, 'name' =>"Sangailu",
                'county_id' => 8, 'name' =>"Ajawa",
                'county_id' => 8, 'name' =>"Batalu",
                'county_id' => 8, 'name' =>"Buna",
                'county_id' => 8, 'name' =>"Bute",
                'county_id' => 8, 'name' =>"Godoma",
                'county_id' => 8, 'name' =>"Gurar",
                'county_id' => 8, 'name' =>"Korondile",
                'county_id' => 8, 'name' =>"Jogbaru",
                'county_id' => 8, 'name' =>"Khorof Harar",
                'county_id' => 8, 'name' =>"Township",
                'county_id' => 8, 'name' =>"Hothan",
                'county_id' => 8, 'name' =>"Wagberi",
                'county_id' => 8, 'name' =>"Wajir Bor",
                'county_id' => 8, 'name' =>"Wargadud",
                'county_id' => 8, 'name' =>"Adamsajide",
                'county_id' => 8, 'name' =>"Arbajahan",
                'county_id' => 8, 'name' =>"Boji Heri",
                'county_id' => 8, 'name' =>"Dela",
                'county_id' => 8, 'name' =>"El-Nur",
                'county_id' => 8, 'name' =>"Eldas",
                'county_id' => 8, 'name' =>"Ganyure",
                'county_id' => 8, 'name' =>"Griftu",
                'county_id' => 8, 'name' => "Hadado",
                'county_id' => 8, 'name' =>"Lakole South",
                'county_id' => 8, 'name' =>"Tula-Tula",
                'county_id' => 8, 'name' =>"Wagalla",
                'county_id' => 8, 'name' =>"Benane",
                'county_id' => 8, 'name' =>"Burder",
                'county_id' => 8, 'name' =>"Dif",
                'county_id' => 8, 'name' =>"Dilmanyale",
                'county_id' => 8, 'name' =>"Habaswein Township",
                'county_id' => 8, 'name' =>"Kulaaley",
                'county_id' => 8, 'name' =>"Lagboghol South",
                'county_id' => 8, 'name' =>"Sabule",
                'county_id' => 9, 'name' => "Banissa",
                'county_id' => 9, 'name' => "Dandu",
                'county_id' => 9, 'name' => "Derkale",
                'county_id' => 9, 'name' => "Gither",
                'county_id' => 9, 'name' =>  "Guba",
                'county_id' => 9, 'name' => "Malkamari",
                'county_id' => 9, 'name' =>  "Takaba North",
                'county_id' => 9, 'name' =>  "Takaba South",
                'county_id' => 9, 'name' =>  "Barwako",
                'county_id' => 9, 'name' => "Border Point One",
                'county_id' => 9, 'name' => "Bula Mpya",
                'county_id' => 9, 'name' => "Bulla Jamhuria",
                'county_id' => 9, 'name' => "Neboi",
                'county_id' => 9, 'name' => "Shaf Shafey",
                'county_id' => 9, 'name' => "Township Kamoro",
                'county_id' => 9, 'name' => "Alango Gof",
                'county_id' => 9, 'name' =>  "Arabia",
                'county_id' => 9, 'name' => "Bur Abor",
                'county_id' => 9, 'name' =>  "Fino",
                'county_id' => 9, 'name' => "Hareri",
                'county_id' => 9, 'name' => "Kalaliyo East",
                'county_id' => 9, 'name' => "Kalaliyo West",
                'county_id' => 9, 'name' => "Lafey",
                'county_id' => 9, 'name' => "Libehia",
                'county_id' => 9, 'name' => "Waranqara",
                'county_id' => 9, 'name' => "Banissa",
                'county_id' => 9, 'name' => "Dandu",
                'county_id' => 9, 'name' => "Derkale",
                'county_id' => 9, 'name' => "Gither",
                'county_id' => 9, 'name' => "Guba",
                'county_id' => 9, 'name' => "Malkamari",
                'county_id' => 9, 'name' => "Takaba North",
                'county_id' => 9, 'name' => "Takaba South",
                'county_id' => 9, 'name' => "Barwako",
                'county_id' => 9, 'name' =>  "Border Point One",
                'county_id' => 9, 'name' => "Bula Mpya",
                'county_id' => 9, 'name' => "Bulla Jamhuria",
                'county_id' => 9, 'name' => "Neboi",
                'county_id' => 9, 'name' => "Alango Gof",
                'county_id' => 9, 'name' => "Township Kamoro",
                'county_id' => 9, 'name' =>  "Arabia",
                'county_id' => 9, 'name' =>  "Bur Abor",
                'county_id' => 9, 'name' =>  "Fino",
                'county_id' => 9, 'name' =>  "Hareri",
                'county_id' => 9, 'name' =>  "Kalaliyo East",
                'county_id' => 9, 'name' =>  "Kalaliyo West",
                'county_id' => 9, 'name' =>  "Lafey",
                'county_id' => 9, 'name' =>  "Libehia",
                'county_id' => 9, 'name' =>  "Waranqara",
                'county_id' => 10, 'name' =>"Bori",
                'county_id' => 10, 'name' =>"Butiye",
                'county_id' => 10, 'name' =>"Dabel",
                'county_id' => 10, 'name' =>"Damballa Fachana",
                'county_id' => 10, 'name' =>"Godoma",
                'county_id' => 10, 'name' =>"Golole",
                'county_id' => 10, 'name' =>"Heillu",
                'county_id' => 10, 'name' =>"Manyatta",
                'county_id' => 10, 'name' =>"Moyale",
                'county_id' => 10, 'name' =>"Nana",
                'county_id' => 10, 'name' =>"Odda",
                'county_id' => 10, 'name' =>"Sololo",
                'county_id' => 10, 'name' =>"Sololo Makutano",
                'county_id' => 10, 'name' =>"Uran",
                'county_id' => 10, 'name' =>"Rawana",
                'county_id' => 10, 'name' =>"Bubisa",
                'county_id' => 10, 'name' =>"Dukana",
                'county_id' => 10, 'name' =>"Hurri Hills",
                'county_id' => 10, 'name' =>"Illeret",
                'county_id' => 10, 'name' =>"Kalacha",
                'county_id' => 10, 'name' =>"Maikona",
                'county_id' => 10, 'name' =>"North Horr",
                'county_id' => 10, 'name' =>"Dakabaricha",
                'county_id' => 10, 'name' =>"Dirib Gombo",
                'county_id' => 10, 'name' =>"Karare",
                'county_id' => 10, 'name' =>"Mountain",
                'county_id' => 10, 'name' =>"Sagante",
                'county_id' => 10, 'name' =>"Korr",
                'county_id' => 10, 'name' =>"Laisamis",
                'county_id' => 10, 'name' =>"Logologo",
                'county_id' => 10, 'name' =>"Loiyangalani",
                'county_id' => 10, 'name' =>"Mount Kulal",
                'county_id' => 10, 'name' =>"South Horr",
                'county_id' => 11, 'name' =>"Bisan Biliku",
                'county_id' => 11, 'name' =>"Bulesa",
                'county_id' => 11, 'name' =>"Isiolo Central",
                'county_id' => 11, 'name' =>"Isiolo East",
                'county_id' => 11, 'name' =>"Isiolo West",
                'county_id' => 11, 'name' =>"Kipsing",
                'county_id' => 11, 'name' =>"Korbesa",
                'county_id' => 11, 'name' =>"Malka Galla",
                'county_id' => 11, 'name' =>"Merti",
                'county_id' => 11, 'name' =>"Ngare Mara",
                'county_id' => 11, 'name' =>"Oldo-Nyiro",
                'county_id' => 11, 'name' =>"Eresaboru",
                'county_id' => 11, 'name' =>"Garbatula",
                'county_id' => 11, 'name' =>"Garfarsa",
                'county_id' => 11, 'name' =>"Kinna",
                'county_id' => 11, 'name' =>"Kula Mawe",
                'county_id' => 11, 'name' =>"Madogashe",
                'county_id' => 11, 'name' =>"Malkadaka",
                'county_id' => 11, 'name' =>"Rapsu",
                'county_id' => 11, 'name' =>"Sericho",
                'county_id' => 12, 'name' => "Giteretu",
                'county_id' => 12, 'name' =>"Igembe East",
                'county_id' => 12, 'name' =>"Igembe South",
                'county_id' => 12, 'name' =>"Igembe South East",
                'county_id' => 12, 'name' =>"Igembe South West",
                'county_id' => 12, 'name' =>"Kangeta",
                'county_id' => 12, 'name' =>"Kiegoi",
                'county_id' => 12, 'name' =>"Njia",
                'county_id' => 12, 'name' =>"Mailo Tatu",
                'county_id' => 12, 'name' =>"Maua East",
                'county_id' => 12, 'name' =>"Maua North",
                'county_id' => 12, 'name' =>"Maua South",
                'county_id' => 12, 'name' =>"Stadium",
                'county_id' => 12, 'name' =>"Akirang'ondu",
                'county_id' => 12, 'name' =>"Antuabetwe kiongo",
                'county_id' => 12, 'name' =>"Antuambui",
                'county_id' => 12, 'name' =>"Athiru Runjine",
                'county_id' => 12, 'name' =>"Kabachi",
                'county_id' => 12, 'name' =>"Naathu",
                'county_id' => 12, 'name' =>"Ntunene",
                'county_id' => 12, 'name' =>"Akithi",
                'county_id' => 12, 'name' =>"Kianjai",
                'county_id' => 12, 'name' => "Kitheo",
                'county_id' => 12, 'name' =>"Mbeu",
                'county_id' => 12, 'name' =>"Mituntu",
                'county_id' => 12, 'name' =>"Nkomo",
                'county_id' => 12, 'name' =>"Karama",
                'county_id' => 12, 'name' =>"Kigucwa",
                'county_id' => 12, 'name' =>"Mikinduri",
                'county_id' => 12, 'name' =>"Muthara",
                'county_id' => 12, 'name' =>"Thangatha",
                'county_id' => 12, 'name' =>"Cathedral",
                'county_id' => 12, 'name' =>"Central",
                'county_id' => 12, 'name' =>"Commercial",
                'county_id' => 12, 'name' =>"Gakoromone",
                'county_id' => 12, 'name' =>"Hospital",
                'county_id' => 12, 'name' =>"Kaaga",
                'county_id' => 12, 'name' =>"Milimani",
                'county_id' => 12, 'name' =>"Mwendantu",
                'county_id' => 12, 'name' =>"Stadium",
                'county_id' => 12, 'name' =>"Chugu",
                'county_id' => 12, 'name' =>"Giaki",
                'county_id' => 12, 'name' =>"Kiirua",
                'county_id' => 12, 'name' =>"Kirimara",
                'county_id' => 12, 'name' =>"Kisima",
                'county_id' => 12, 'name' =>"Ntakira",
                'county_id' => 12, 'name' =>"Ontulili",
                'county_id' => 12, 'name' =>"Ruiri",
                'county_id' => 12, 'name' =>"Thuura",
                'county_id' => 12, 'name' =>"Timau",
                'county_id' => 12, 'name' =>"Kisima",
                'county_id' => 12, 'name' =>"Kirua",
                'county_id' => 12, 'name' =>"Ruiri",
                'county_id' => 12, 'name' =>"Gatimbi",
                'county_id' => 12, 'name' =>"Kariene",
                'county_id' => 12, 'name' =>"Katheri",
                'county_id' => 12, 'name' =>"Kiagu",
                'county_id' => 12, 'name' =>"Kibaranyaki",
                'county_id' => 12, 'name' =>"Kibirichia",
                'county_id' => 12, 'name' =>"Kithirune",
                'county_id' => 12, 'name' =>"Mwangathia",
                'county_id' => 12, 'name' =>"Abogeta",
                'county_id' => 12, 'name' =>"Igoji",
                'county_id' => 12, 'name' =>"Igoki",
                'county_id' => 12, 'name' =>"Kanyakine",
                'county_id' => 12, 'name' =>"Mikumbune",
                'county_id' => 12, 'name' =>"Mitiine",
                'county_id' => 12, 'name' =>"Mitunguu",
                'county_id' => 12, 'name' =>"Nkuene",

        ];


        foreach ($wards as $ward) {
            Variety::create($ward);
        }



    }
}
